#!/bin/bash

set -ex

source $(dirname "$0")/env_setup.sh

setup_lint_env

# Ignore the expected and resulting output files generated by unittests for the aggregate_file script
# These are formatted poorly are only meant to be used for testing purposes
black --check --diff src/ tests/
isort --profile black --check --diff src/ tests/
