DOC_ID_KEY = "doc_id"
CHUNK_ID_KEY = "chunk_id"
DOC_TEXT_KEY = "text"
EMBEDDING_KEY = "embedding"
EMBEDDING_HIDDEN_DIM_KEY = "embedding_hidden_dim"
SUPPORTED_FILE_EXTENSIONS = [".pdf", ".txt", ".docx", ".doc", ".rtf", ".csv", ".md", ".py", ".log"]
SUPPORTED_HTML_TAGS = ["p", "table"]
EVALUATION_DIR = "./evaluation_data"
EVALUATION_MAX_FILE_SIZE = 5 * 1000 * 1000  # 5 MB
