DB_TYPE: faiss
GPU: false
SIMILARITY_THRESHOLD: 0.95
USE_EXISTING_INDEX: false
INDEX_PATH: vectorDB_index_save/
SIMILARITY_FN: cosine
METADATA_PATH: vectorDB_metadata_save/
MILVUS_DB_NAME: rag_milvus_db
MILVUS_DB_COLLECTION_NAME: AutoGluonRAG_Milvus_DB_Collection
MILVUS_INDEX_PARAMS:
  metric_type: L2
  index_type: IVF_FLAT
  params: 
    nlist: 256
MILVUS_SEARCH_PARAMS:
  metric_type: L2
  params:
    nprobe: 10
MILVUS_CREATE_PARAMS: 
  metric_type: L2
