data:
  chunk_size: 512
  chunk_overlap: 64
  data_dir: autogluon_docs

embedding:
  embedding_model: BAAI/bge-large-en
  pooling_strategy: cls
  normalize_embeddings: false
  hf_model_params: null
  hf_tokenizer_init_params: null
  hf_tokenizer_params: 
    truncation: true
    padding: true
  hf_forward_params: null
  normalization_params: {'p': 2, 'dim': 1, 'eps': 1e-12}

vector_db:
  db_type: faiss
  params: {gpu: False}
  similarity_threshold: 0.95
  similarity_fn: cosine
  use_existing_vector_db: false
  num_gpus: 0
  vector_db_index_path: s3://autogluon-rag-github-dev/vectorDB_index_save/faiss/index.idx
  metadata_index_path: s3://autogluon-rag-github-dev/vectorDB_metadata_save/faiss/metadata.json

retriever:
  top_k_embeddings: 5
  use_reranker: false
  reranker_model_name: BAAI/bge-large-en
  reranker_batch_size: 32
